# Generated by Django 5.0.6 on 2024-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_files/')),
                ('csv_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CSV File Data',
                'verbose_name_plural': 'CSV File Data',
            },
        ),
        migrations.CreateModel(
            name='ProcessedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('mean_value', models.FloatField()),
                ('median_value', models.FloatField()),
                ('mode_value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Processed Results',
                'verbose_name_plural': 'Processed Results',
            },
        ),
    ]
